/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: rriyas <rriyas@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/07/26 13:54:26 by rriyas            #+#    #+#             */
/*   Updated: 2022/10/23 17:45:51 by rriyas           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../inc/minishell.h"

t_shell zundra;

/**
 * @brief Function to handle various signals in the program
 *
 * @param sig - signal recieved by the program
 */
void sig_handler(int sig)
{
	if (sig == SIGINT) //needs work
	{
		write(1, "\n", 1);
		rl_on_new_line();
		exit(0);
	}
}

/**
 * @brief				Phase 1 of the shell - commands typed by th user are split into tokens
 *
 */
void lexer(char **argv)
{

}

/**
 * @brief				Phase 2 of the shell - parsing of tokens generated by the lexer happens here
 *
 * @return t_command*	Linked list of commands in the current pipeline
 */
t_command *parser()
{
	return NULL;
}

/**
 * @brief			Phase 3 of the shell - execution of commands takes place here
 *
 * @param cmd		Linked list of commands to execute in the current pipeline
 * @return int		Status code of last executed command
 */
int executor(t_command *cmd)
{
	t_command *iterator;
	char **cmd_argv;
	int i;

	prepare_pipes();
	while (iterator)
	{
		iterator = cmd;
		zundra.cmds = iterator;
		cmd_argv = prepare_cmd_args(iterator->words);
		cmd_executor(iterator, cmd_argv);
		iterator = iterator->next;
	}
	i = 0;
	while (i < zundra.num_of_cmds)
	{
		wait(0);
		i++;
	}
	free_commands(cmd);
	return status_code();
}

int main(int argc, char **argv, char **envp)
{
	char *s;
	t_command *cmd;
	(void)argc;
	(void)argv;

	signal(SIGINT, &sig_handler);
	signal(SIGQUIT, &sig_handler);
	zundra.envp = envp;
	while (2)
	{
		s = readline("minishell ^-^ : ");
		add_history(s);
		lexer(argv);
		cmd = parser();
		executor(cmd);
		free(s);
	}
	return (0);
}